/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts,scss}",
  ],
  theme: {
    extend: {
      colors: {
        'surface':                   '#fff8f5',
        'surface-dim':               '#e1d8d4',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#fbf2ed',
        'surface-container':         '#f5ece7',
        'surface-container-high':    '#efe7e2',
        'surface-container-highest': '#e9e1dc',
        'on-surface':                '#1e1b18',
        'on-surface-variant':        '#4d4635',
        'outline':                   '#7f7663',
        'outline-variant':           '#d0c5af',
        'primary':                   '#735c00',
        'on-primary':                '#ffffff',
        'primary-container':         '#d4af37',
        'secondary':                 '#875040',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#fdb5a1',
        'background':                '#fff8f5',
        'on-background':             '#1e1b18',
        'surface-variant':           '#e9e1dc',
      },
      fontFamily: {
        sans: ['"LXGW WenKai"', 'serif'],
        serif: ['"LXGW WenKai"', 'serif'],
      },
      fontSize: {
        'display-lg':        ['64px',  { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['40px',  { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'headline-xl':       ['48px',  { lineHeight: '1.2' }],
        'headline-lg':       ['40px',  { lineHeight: '1.2' }],
        'headline-md':       ['28px',  { lineHeight: '1.3' }],
        'body-lg':           ['18px',  { lineHeight: '1.6' }],
        'body-md':           ['16px',  { lineHeight: '1.6' }],
        'label-sm':          ['12px',  { lineHeight: '1.4', letterSpacing: '0.1em' }],
        'label-xs':          ['11px',  { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'caption':           ['12px',  { lineHeight: '1.5' }],
      },
      spacing: {
        'stack-xs':            '8px',
        'stack-sm':            '16px',
        'stack-md':            '24px',
        'stack-lg':            '48px',
        'gutter':              '24px',
        'margin-edge':         '24px',
        'margin-page':         '64px',
        'section-gap-desktop': '120px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        silk: {
          "primary":          "#735c00",
          "primary-content":  "#ffffff",
          "secondary":        "#875040",
          "secondary-content":"#ffffff",
          "accent":           "#d4af37",
          "accent-content":   "#1e1b18",
          "neutral":          "#1e1b18",
          "neutral-content":  "#ffffff",
          "base-100":         "#fff8f5",
          "base-200":         "#f5ece7",
          "base-300":         "#efe7e2",
          "base-content":     "#1e1b18",
          "--rounded-box":    "0.5rem",
          "--rounded-btn":    "0.375rem",
        },
      },
    ],
    darkTheme: false,
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
